spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_reservation?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9191
